---
title: 'Week 2: Assignment Answer Key'
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

1.  Basic Expressions

```{r}
2 - 10
3 * 5
9 / 2
5 - 3 * 2
(5 - 3) * 2
4 ** 2
8 / 2 ** 2
```

2.  Basic Variables

```{r}
mass_lbs <- 3.5
mass_kg <- mass_lbs / 2.2046
mass_kg
```

3.  More Variables

```{r}
grams <- 250
number <- 3
biomass <- grams * number
biomass_kg <- biomass / 1000
print(biomass_kg)
```

4.  Built-In Functions

```{r}
abs(-15.5)

round(4.483847, 1)

round(3.8, 0)

toupper("species")

tolower("SPECIES")

value <- sqrt(2.6)
value <- round(value, 2)
value

round(sqrt(2.6), 2)
```

5.  Modify the Code

```{r}
# grams of carbon per sq. meter
site1_g_carbon_m2_day <- 5
site2_g_carbon_m2_day <- 2.3

# number of sq. meters
site1_area_m2 <- 200
site2_area_m2 <- 450

# daily NPP per site
site1_npp_day <- site1_g_carbon_m2_day * site1_area_m2
site2_npp_day <- site2_g_carbon_m2_day * site2_area_m2

# a.  The sum of the total daily NPP for the two sites combined.
total_npp_day <- site1_npp_day + site2_npp_day
total_npp_day

# b.  The difference between the total daily NPP for the two sites.
daily_diff <- abs(site1_npp_day - site2_npp_day)
daily_diff

# c.  The total NPP over a year for the two sites combined.
total_npp_year <- total_npp_day * 365
total_npp_year
```

6.  Basic Vectors

```{r}
numbers <- c(5, 2, 26, 8, 16)

length(numbers)

numbers[3]

min(numbers)

max(numbers)

mean(numbers)

numbers[1:3]

sum(numbers)
```

7.  Null Vectors

```{r}
numbers <- c(7, 6, 22, 5, NA, 42)

min(numbers, na.rm = TRUE)
max(numbers, na.rm = TRUE)
mean(numbers, na.rm = TRUE)
sum(numbers, na.rm = TRUE)
```

8.  Shrub Volume Vectors

```{r}
length <- c(2.2, 2.1, 2.7, 3.0, 3.1, 2.5, 1.9, 1.1, 3.5, 2.9)
width <- c(1.3, 2.2, 1.5, 4.5, 3.1, NA, 1.8, 0.5, 2.0, 2.7)
height <- c(9.6, 7.6, 2.2, 1.5, 4.0, 3.0, 4.5, 2.3, 7.5, 3.2)

#1
volume <- length * width * height
volume

#2
sum(volume, na.rm = TRUE)

#3

height[length > 2.5]

#4
height[height > 5]

#5
height[1:5]

#6
volume[1:3]

print("Challenge")
num_shrubs <- length(volume)
volume[(num_shrubs - 4):num_shrubs]
```
