---
title: "Week 13 Assignment"
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(tidyverse)
```

### 1. For Loop Basics (30 pts)

1a.

```{r}
numbers <- c(1, 2, 3, 4, 5)
for (number in numbers){
  print(3 * number)
}

```

1b.

```{r}
mass_lbs <- c(2.2, 3.5, 9.6, 1.2)
```

```{r}
for (mass in mass_lbs) {
  mass_kgs <- 2.2 * mass
  print(mass_kgs)
}
```

1c. 

```{r}
# birds = c("robin", "woodpecker", "blue jay", "sparrow")
# for (i in 1:length(_________)){
#   print(birds[__])
# }
```

```{r}
birds = c('robin', 'woodpecker', 'blue jay', 'sparrow')
for (i in 1:length(birds)){
  print(birds[i])
}
```

1d. 

```{r}
radius <- c(1.3, 2.1, 3.5)
# areas <- vector(_____ = "numeric", length = ______)
# for (__ in 1:length(________)){
#   areas[__] <- pi * radius[i] ^ 2
# }
# areas
```

```{r}
areas <- vector(mode = "numeric", length = length(radius))
for (i in 1:length(areas)){
  areas[i] <- pi * radius[i] ^ 2
}
areas
```

1e. 

```{r}
lengths = c(1.1, 2.2, 1.6)
widths = c(3.5, 2.4, 2.8)
# areas <- vector(length = __________)
# for (i in _____) {
#   areas[__] <- lengths[__] * widths[__]
# }
# areas
```

```{r}
areas <- vector(length = length(lengths))
for (i in 1:length(lengths)) {
  areas[i] <- lengths[i] * widths[i]
}
areas
```

### 2. Size Estimates by Name (30 pts)

```{r}
mass_from_length <- function(length, dino_group) {
    if (dino_group == 'Stegosauria') {
        mass <- 10.95 * length ^ 2.64
    } else if (dino_group == 'Theropoda') {
        mass <- 0.73 * length ^ 3.63
    } else if (dino_group == 'Sauropoda') {
        mass <- 214.44 * length ^ 1.46
    } else {
        mass <- 25.37 * length ^ 2.49
    }
    return(mass)
}

dino_data <- read_csv("../data_raw/dinosaur_lengths.csv")
```

2a.

```{r}
lengths <- dino_data$lengths
species <- dino_data$species
masses <- vector(length = length(lengths))
for (i in 1:length(lengths)){
    masses[i] <- mass_from_length(lengths[i], species[i])
}
head(masses)
```

2b.

```{r}
dino_data$masses = masses
head(dino_data)
```

2c.

```{r}
dino_data %>%
  group_by(species) %>%
  summarize(avg_mass = mean(masses))
```


### 3. Multi-file Analysis (40 pts)

3a. 
```{r}
collar_data_files = list.files(path = "../data_raw/",
                               pattern = "collar-data-.*.txt",
                               full.names = TRUE)

num_data_files = length(collar_data_files)
output = data.frame(file_name = character(num_data_files),
                    max_lat = numeric(num_data_files),
                    min_lat = numeric(num_data_files),
                    observations = numeric(num_data_files),
                    stringsAsFactors = FALSE)

print("3a")

for (i in 1:length(collar_data_files)){
  data = read.csv(collar_data_files[i])
  p <- ggplot(data, aes(x = long, y = lat)) + geom_path() + labs(title = collar_data_files[i])
  print(p)
}

```

3b. 
```{r fig.dim=c(2,2)}
for (i in 1:length(collar_data_files)){
  data = read.csv(collar_data_files[i])
  p <- ggplot(data, aes(x = long, y = lat)) + geom_path() + labs(title = collar_data_files[i])
  print(p)
  output$file_name[i] = collar_data_files[i]
  output$max_lat[i] = max(data$lat)
  output$min_lat[i] = min(data$lat)
  output$observations[i] = nrow(data)
}

output
```

### 4. DNA or RNA (20 points)

4b. 
```{r}
library(tidyverse)

dna_or_rna <- function(sequence){
  # Determines if a character string represents DNA, RNA, or is unknown
  # by searching the character string for the unique base pairs t & u.
  if (str_count(sequence, "t") > 0){
    type = "DNA"
  } else if (str_count(sequence, "u") > 0){
    type = "RNA"
  } else {
    type = "UNKNOWN"
  }
  return(type)
}

seq1 <- "ttgaatgccttacaactgatcattacacaggcggcatgaagcaaaaatatactgtgaaccaatgcaggcg"
seq2 <- "gauuauuccccacaaagggagugggauuaggagcugcaucauuuacaagagcagaauguuucaaaugcau"
seq3 <- "gaaagcaagaaaaggcaggcgaggaagggaagaagggggggaaacc"

dna_or_rna(seq1)
dna_or_rna(seq2)
dna_or_rna(seq3)
```

```{r}
sequences <- c("ttgaatgccttacaactgatcattacacaggcggcatgaagcaaaaatatactgtgaaccaatgcaggcg",
              "gauuauuccccacaaagggagugggauuaggagcugcaucauuuacaagagcagaauguuucaaaugcau",
              "gaaagcaagaaaaggcaggcgaggaagggaagaagggggggaaacc",
              "guuuccuacaguauuugaugagaaugagaguuuacuccuggaagauaauauuagaauguuuacaacugcaccugaucagguggauaaggaagaugaagacu",
              "gauaaggaagaugaagacuuucaggaaucuaauaaaaugcacuccaugaauggauucauguaugggaaucagccggguc")
```

4c.

```{r}
for (sequence in sequences){
  print(dna_or_rna(sequence))
}
```


4d.
```{r}
df <- data.frame(type = vector(mode = "character", length = length(sequences)),
                 sequence = vector(mode = "character", length = length(sequences)))

for (i in 1:length(sequences)) {
  df$sequence[i] <- sequences[i]
  df$type[i] <- dna_or_rna(sequences[i])
}

as.tibble(df)
```


4e. OPTIONAL

```{r}
sapply(sequences, dna_or_rna)
```

4f. OPTIONAL

```{r}
seq_df <- as.data.frame(sequences)
seq_df |> 
  rowwise() |> 
  mutate(type = dna_or_rna(sequences), .before = sequences)
```

