---
title: "Assignment 7, Part I"
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE}
library(tidyverse)
```

### 2. When Did You Knit This Document? (5 pts)

```{r}
#a
today()

#b
now()
```

### 3. Plant Vouchers (20 pts)

```{r}
vouchers <- read_csv("https://raw.githubusercontent.com/weecology/DNA_metabarcoding/master/data/collection_data/plant_voucher_collection.csv")
```

```{r}
#a
vouchers <- vouchers %>% 
  mutate(collection_date = make_date(year = year,
                                     month = month,
                                     day = day), .after = day)
vouchers

#b
min(vouchers$collection_date)

#c
max(vouchers$collection_date)

#d
as.duration(interval(min(vouchers$collection_date), max(vouchers$collection_date)))

#e
vouchers %>% 
  mutate(DOY = yday(collection_date), .after = collection_date)
```

### 4. NDVI from the Santa Rita Experimental Range (20 pts)

```{r}
phenocam <- read_csv("neon_srer_ndvi_phencom.csv", skip = 17, col_names = TRUE, 
                    col_types = "ccncc") %>% 
  select(date, local_std_time, contains("mean"), NDVI_c)
```

```{r}
#a create datetime column using unite
phenocam <- phenocam %>% 
  unite("datetime", date, local_std_time, sep = " ")
phenocam

#b convert to POSIXct using lubridate
phenocam <- phenocam %>% 
  mutate(datetime = ymd_hms(datetime))
phenocam

#c duration of dataset
as.duration(interval(min(phenocam$datetime), max(phenocam$datetime)))

#d make separte columns for year, month, and DOY
phenocam <- phenocam %>% 
  mutate(year = year(datetime),
         month = month(datetime),
         DOY = yday(datetime))
phenocam

#e calculate mean NVDI per month per year
phenocam %>% 
  group_by(year, month) %>% 
  summarise(mean_NVDI = mean(NDVI_c, na.rm = TRUE))

```


### 5. Vectors (10 pts)

```{r}
lyrics <- c("This ain't Texas (woo),", 
           "ain't no hold 'em (hey)/",
           "So lay your cards down, down, down, down")
```


```{r}
print("2a:")
str_length(lyrics)

print("2b:")
str_detect(lyrics, "Texas")

print("2c:")
str_count(lyrics, "down")

print("2d:")
str_extract(lyrics, "\\((.*?)\\)")
```

### 6. Dugout Data (15 pts)

```{r}
dugout <- read_csv("elevation_2017.csv") %>% 
  rename(SoilSalinity = `Soil Salinity`,
         SoilZone = `Soil Zone`,
         MajorSalts = `Major Salts in groundwater`)
dugout
```

```{r}
print("3a:")
dugout %>% 
  filter(str_detect(SoilSalinity, "slight"))

print("3b:")
dugout %>% 
  filter(str_detect(Site_ID, "[A-Z]+"))

print("3c:")
dugout %>% 
  mutate(pH = str_replace(pH, "acid", "acidic"))
```

### 7. Santa Cruz Rodents (20 pts)

```{r}
rodents <- read_csv("capture_data.csv")
```

```{r}
print("Read in data:")
rodents <- rodents %>% 
  rename(TailLength = `Tail length`,
         HairSample = `Hair sample (Y/N)`,
         Position = `Position (R/L)`)

print("4a:")
rodents %>% 
  filter(str_length(Species) != 4)

print("4b:")
rodents %>% 
  mutate(TailLength = str_remove(TailLength, "~"))

print("4c")
rodents <- rodents %>% 
  mutate(Species = str_remove(Species, "\\?"))
rodents

print("4d:")
rodents <- rodents %>% 
  mutate(HairSample = str_replace(HairSample, "\\?", NA_character_),
         Position = str_replace(Position, "\\?", NA_character_))
rodents
```
