---
title: 'Week 9: Reproducibility in RStudio'
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reproducibility in RStudio

In this week's lesson, we will be talking broadly about how to make our data analyses reproducible.

We will do this through 2 different approaches.
1) Reproducibility in RStudio
2) Using git/GitHub for version control

For today's lesson, we will focus on how we can increase reproducibility within RStudio.

## R vs. RStudio

Before we begin, it is worth reminding ourselves of the difference between R and RStudio.

We are making the shift from working in Posit Cloud to using R and RStudio on your own device, meaning you should have both R and RStudio downloaded on your computer.

For most of us, even though we have downloaded the R software, we will likely never interact with the R program directly; I personally never open up R on my own computer.

Instead, in order to code in R and work with the R software, we will want to open up RStudio. Like it does in Posit Cloud, RStudio on our own computers connects to the R software that we have downloaded and let's us interact with R within the RStudio environment. So while I never personally open up R software directly, I frequently open up RStudio and work with R there!

## Introduction to Reproducibility

Throughout the course, we have talked about many of the  the idea of reproducbility, b
Goal - rerun full analysis with a single click (or command)
* First step - Make sure your code runs anytime and anywhere
  * next day (who has gotten code working & had it not work the next day?)
	* desktop vs. laptop
	* collaborators
	* advisor

1. Make sure things you did before don't matter

* Computers store the results of each command run in sequence
* Change something
* Looks like it still works
* Only works because of something you did earlier in the same session

2. Clearing environments and restarting R

* Clear R environment using the broom icon on the `Environment` tab.
  * Doesn't unload packages
  * Useful when developing code
* Restart R to get a clean environment
  * Works locally (not in Posit Cloud; `Session` -> `Restart R` always reloads environment)
  * Does unload packages
  * Useful for making sure everything works
  * As long is it doesn't secretly reload things
* Run entire file using `Source` button or `Ctrl-Shift-S`
* Makes sure that the code runs fully and produces desired result

3. Stop saving the current state of the environment

* Stop R from storing the state of the environment
* When you close RStudio it will often ask if you want to save your workspace
* *Start to close RStudio*
* *Show Save dialog*
* Or on Posit Cloud it will just do this automatically
* If you do this is will get reloaded when you start R, even when you restart it
  as described above
* Stop this by `Tools` -> `Global Options` -> `General` ->
  `Save workspace to ~/.RData on exit` -> `Never`
* Unclick `Restore .RData into workspace at startup` 

4. Make sure code works on other computers

* Don't use `setwd()`
    * Use projects and relative paths
    * `data/mydata.csv` not `C:\Users\Batman\DataCarp\data\mydata.csv`
* Write code that works on all operating systems
    * Filenames in code should match actual names exactly, including capitalization
    * Use `/` instead of `\` or `\\` in paths
 
 5. Clean up extra code

* Remove experiments from your code
* Or at least comment them out
* Remove `install.packages()` lines from your code
* Avoid reinstalling packages repeatedly

### Project Structure


### Introduction

* Learn how to organize a computational project
* Many benefits to good organization & documentation
    * Understand all project components
    * Work more efficiently
    * Easier for collaboration
    * Including with your future self
* Save a lot of time & frustration in long run, even if it’s time-consuming and frustrating to do it right initially

* Good file structure
    * All project files in one main folder
    * Subfolders (data, R, etc.)
* Main folder is R project
    * Self-contained project
    * Use relative instead of absolute paths
* Good folder & file names
    * Descriptive but not too long
    * No spaces
    * Consistent format
* README
    * Everything someone needs to know to understand project
* Raw data
    * In separate folder from cleaned data
    * Never change!
    * Each file should have metadata
* Scripts with code
    * Relative file paths to read in and create files
    * Lots of comments
    * Order: libraries, data, user-created functions, everything else
    * Good variable & column names
* Two methods to deal with different versions of same file
    * Good = consistent naming scheme
        * Each copy has date or version number
        * Don’t call anything final, cause no file ever is! 
    * Better = version control, only have one copy of each file
* Running all scripts
    * Good = description of order to run each script in README
    * Better = script to run all scripts
    * Best = Make
* Combine code output and text in single document, e.g., knitr

### Goal of good project structure

* Reproducibility = ability to get same results from set of data & code
* Give entire project folder to someone else (or your future self!), they can understand all parts and recreate your results, figures, documents, etc. 
* Improving reproducibility makes YOUR life easier! 


### R Projects

The best way to work in RStudio is through R Projects (.Rproj files).

### Example project walk-through
Download [example project]({{ site.baseurl }}/data/example_project.zip). 


### File Paths

Why do I believe so strongly in working in RProjects? There are a few reasons. In part, it is because R Projects work so well with the version control that we will be learning in the next lesson. The other reason is file paths!

### (optional) If Using Posit Cloud

* So far in this course we've been using Posit Cloud and placing data files where R knows to find them for you
* Working with data files on your own computer is a little more complicated
* But in this lesson we'll learn how to do this effectively

### Introduction to Paths

* To use data stored on a computer we need to tell R where it is
* This is done using paths
* This is a description of the directories where our files are stored
* Let's go to the course website and download some data
* https://datacarpentry.org/semester-biology/materials/datasets
* This page contains all of the data we use in class
* Download Shrub Dimensions data
* If we click on this link it will download, but where did it download to
* Click on the arrow to 'Show in Folder'
* The details will look different depending on the operating system
* But, generally, across the top you'll see the folder that things are stored in

* Go back to RStudio
* If we try to load this data just using it's filename it won't work

```r
data = read.csv("shrub-dimensions-labeled.csv")
```

* Returns the error "Cannot open file", "No such file or directory"
* That's because it can't find the file where we've tried to load it from


* Paths can be either relative or absolute
* We'll start with absolute, which always describes exactly where something is on the computer
* Data file is stored in the `Downloads` subdirectory of our `Home` directory
* `Home` directory varies by operating system
* On mac and Linux it is `/home/username`
* Within that is the `Downloads` directory

```r
# OSX/Linux
data = read.csv('/home/ethan/Downloads/shrub-dimensions-labeled.csv')
```

* This successfully loads the data because we've told it exactly where the file is
* On Windows change `home` to `Users`

```r
# Windows
data = read.csv('/Users/ethan/Downloads/shrub-dimensions-labeled.csv')
```

* Folders/Directories are separate by `/` with the file name at the end
* Windows shows `\` or `\\` as the separator, but `/` works on all operating systems so use it
* Include the file extension (the part after the `.`)

* Paths can also be relative

```r
'Downloads/shrub-dimensions-labeled.csv'
```

* "From where I am the shrub-dimensions file is in the Downloads subdirectory"
* The absolute & relative paths here are the same if R thinks it's in `/home/ethan/`

### Find out where you are

* To find out where R is use `getwd()`

```r
getwd()
```

* "get working directory"
* The "working directory" is where the program starts from

### Loading data

* For data in the working directory just use the file name

```r
shrub_data <- read.csv('shrub-dimensions-labeled.csv')
```

* This is a relative path, because the file is in the working directory the only remaining piece is the name

* One way to ensure that a file is in the working directory is to download it using `download.file()`

* For data not in the working directory there are two options
    * tell R where it is
    * change the working directory to where it is
* Changing the working directory is common
    * Who here uses `setwd` regularly?
    * Does that ever cause any issues?
        * Working on a different computer?
        * Working with someone else's files?
* In general, using `setwd` means that your code will only work on a single computer
* That's bad, so we want to have the working directory automatically and use relative paths

### Projects

* The simplest way to do this is using RStudio Projects

* (Posit Cloud) In fact we've already been using them
* (Posit Cloud) Every time you click on an assignment or click `New Project` this creates a new project

* Each project is a self-contained unit of work in a single folder/directory
* Treat all locations as relative to that single directory
* To do this in regular RStudio we use projects
* `File` -> `New Project` -> `New Directory` -> `New Project` -> datacarp
* Or use `Existing Directory` to choose an existing directory
* Creates .Rproj file
    * Isn’t project itself
    * Contains project info
    * Don’t change manually
* Then place your data files in the project directory (or a subdirectory)
* *copy shrub-dimensions-labeled.csv to a /home/user/datacarp/*

```r
# OSX/Linux
data = read.csv('shrub-dimensions-labeled.csv')
```

* It is common to store data in a subdirectory
* `New Folder` -> data -> `OK`
* `File checkbox` -> `More` -> `Move` -> data

```r
# OSX/Linux
data = read.csv('data/shrub-dimensions-labeled.csv')
```

* Can switch between projects using `File` -> `Recent Projects` or `Open Project`
* Keeps track the state of RStudio when you last worked with that project

### Sharing code

* This idea of projects as folders is also important for how we share code
* Version control, which we'll have the opportunity to learn about later, works with the projects as folder structure
* We can also zip a the project folder and send it to someone else and they can work with it

