---
title: 'Assignment 12: Conditionals'
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Assignment

### 1. Choice Operators (20 pts)

```{r}
w <- 10.2
x <- 1.3
y <- 2.8
z <- 17.5
colors <- c("red", "blue", "green")
masses <- c(45.2, 36.1, 27.8, 81.6, 42.4)
dna1 <- "attattaggaccaca"
dna2 <- "attattaggaacaca"
```

```{r}
### Code solution for Choice Operators

print("1a")
# a.  `w` is greater than 10
w > 10

print("1b")
# b.  `w` + `x` is less than 15
w + x < 15

print("1c")
# c.  `x` is greater than `y`
x > y

print("1d")
# d. Each value in `masses` is greater than 50.
masses > 40

print("1e")
# f.  `dna1` is the same as `dna2`
dna1 == dna2

print("1f")
# g.  `dna1` is not the same as `dna2`
dna1 != dna2

print("1g")
# h. `w` is greater than `x`, or `y` is greater than `z`
w > x | y > z

print("1h")
# i.  `x` times `w` is between 13.2 and 13.5
13.2 < x * w & x * w < 13.5  # | (a pipe) will return TRUE for all values.

print("1i")
# j. Each mass in `masses` is between 30 and 50.
masses > 30 & masses < 50
```

### 2. If Statements (20 points)

```{r}
print("2a")
# a. Complete (i.e., copy into your code and them modify) the following `if`
#   statement so that if `age_class` is equal to "sapling" it sets `y <- 10`.

age_class = "sapling"
if (age_class == "sapling"){
  y <-10
}
y

print("2b")
# b. Complete the following `if` statement so that if `age_class` is equal to
#   "sapling" it sets `y <- 10` and if `age_class` is equal to "seedling" it
#   sets `y <- 5`.

age_class = "seedling"
if (age_class == "sapling"){
  y <-10
} else if (age_class == "seedling"){
  y <- 5
}
y


print("2c")
# c. Complete the following `if` statement so that if `age_class` is equal to
#   "sapling" it sets `y <- 10` and if `age_class` is equal to "seedling" it
#   sets `y <- 5` and if `age_class` is something else then it sets the value of
#   `y <- 0`.

age_class = "adult"
if (age_class == "sapling"){
  y <-10
} else if (age_class == "seedling") {
  y <- 5
} else {
  y <- 0
}
y

print("2d")
# d. Convert your conditional statement from (c) into a function that takes
#   `age_class` as an argument and returns `y`. Call this function 5 times, once
#   with each of the following values for `age_class`: "sapling", "seedling",
#   "adult", "mature", "established".

get_y_from_age_class <- function(age_class){
  if (age_class == "sapling"){
    y <-10
  } else if (age_class == "seedling") {
    y <- 5
  } else {
    y <- 0
  }
  return(y)
}

get_y_from_age_class("sapling")
get_y_from_age_class("seedling")
get_y_from_age_class("adult")
get_y_from_age_class("mature")
get_y_from_age_class("established")
```

### 3. If Statements in Functions (20 points)

```{r}
# Solution to If Statements in Functions exercise

print("3a")
double_if_small <- function(number){
  if (number < 26){
    output = number * 2
  } else {
    output = number
  }
  return(output)
}

print("3b")

double_if_small(10)

print("3c")

double_if_small(30)

print("3d")

prediction <- function(x){
  if (x > 0 & x < 15){
      y = 6 + 0.8 * x
  } else if (x > 15 & x < 30) {
      y = 5 + 0.75 * x
  } else {
      y = NA
  }
  return (y)
}

print("3e")
prediction(5)

print("3f")
prediction(26)

print("3g")

prediction(-2)
```

### 4. Size Estimates by Name (20 points)

```{r}
get_mass_from_length <- function(a, b, length){
  mass = a * length ** b
  return (mass)
}

get_mass_from_length_by_name <- function(length, name){
  if (name == "Stegosauria"){
    if (length > 8){
      a = 10.95
      b = 2.64
    } else {
      a = 8.5
      b = 2.8
    }
  }
  else if (name == "Theropoda"){
    a = 0.73
    b = 3.63
  }
  else if (name == "Sauropoda"){
    a = 214.44
    b = 1.46
  }
  else {
    return(NA)
  }
  get_mass_from_length(a, b, length)
}

get_mass_from_length_by_name(10, "Stegosauria")
get_mass_from_length_by_name(8, "Theropoda")
get_mass_from_length_by_name(12, "Sauropoda")
get_mass_from_length_by_name(13, 'Ankylosauria')
```

### 5. Using `dplyr` Choice Functions (20 points)

```{r}
library(dplyr)
library(lterdatasampler)
```

```{r}
print("5a")

crab_size <- 17

if_else(crab_size >= 20, "large", "small")

print("5b")

if_else(crab_size > 20, "large",
        if_else(crab_size > 10, "medium", "small"))

print("5c")

case_when(crab_size > 20 ~ "large",
          crab_size > 10 ~ "medium",
          TRUE ~ "small")

print("5d")

pie_crab %>% 
  mutate(size_category = if_else(size > 20, "large", "small"), .after = size)

print("5e")

pie_crab %>% 
  mutate(size_category3 = case_when(size > 20 ~ "large",
                          size > 10 ~ "medium",
                          TRUE ~ "small"), .after = size)
```
