---
title: 'Peer Code Review: Checklist and Reflection'
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Checklist and Reflection (20 points)

In this .Rmd file, you will find (a) the checklist to complete for the peer code review and (b) a short reflection about the experience.

Once both are completed, knit this document and submit to the Peer Code Review Assignment on D2L.

### GitHub Repo

Whose repo did you review? Include the link to the repo here.

Name:

Link to Repo:

## Checklist

Complete the checklist, where appropriate, based on your review. If you are in visual mode, you can actually "check" the boxes by clicking on them. If you are working in source mode, you will put an `x` inside the square brackets next to each item.

Since you are reviewing a "Work in Progress" project, not all boxed might be checked; that's ok! That will not impact anyone's grade :)

### Repository Setup

-   [ ] I accessed and cloned the repository.
-   [ ] A README is present.
    -   [ ] README explains project purpose.
    -   [ ] README includes reproduction instructions.

### Code Clarity & Readability

-   [ ] Variable names are descriptive.
-   [ ] Code is logically structured.
-   [ ] Helpful comments are included.
-   [ ] Code is generally readable.

**Notes / Comments:**\
\>

### Functionality

-   [ ] Code runs without errors.
-   [ ] Outputs match expectations or are explained.
-   [ ] All file paths are relative.

**Notes / Comments:**\
\>

### Code Organization

-   [ ] Files and folders are logically structured.
-   [ ] Workflow is understandable and modular.
-   [ ] Reproducibility is supported.

**Notes / Comments:**\
\>

### Documentation

-   [ ] README is complete and clear.
-   [ ] RMarkdown file or R scripts include informative text and/or comments.
-   [ ] Data or package requirements are documented.

**Notes / Comments:**\
\>

### Suggestions for Improvement

List **three** actionable suggestions:

1.  

2.  

3.  

## Reflection

Write 7-10 sentences summarizing your review experience:

-   What was done well?
-   What was challenging about this assignment?
-   What did you learn for your own projects?
-   How did you approach constructive feedback?

**Reflection**:

## Submission

Upload the knitted `.pdf` file to the "Peer Code Review" Assignment on D2L.
