---
title: "Week 4 Assignment"
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r message=FALSE}
library(readr)
library(dplyr)
```

```{r message=FALSE}
surveys <- read_csv("surveys.csv")
species <- read_csv("species.csv")
plots <- read_csv("plots.csv")
```

### 2. Portal Data Aggregation (10 pts)

```{r}
# 1. Use the group_by() and summarize() functions to get a count of the number of individuals in each species ID.

surveys %>% 
  group_by(species_id) %>% 
  summarize(count = n())

# 2. Use the group_by() and summarize() functions to get a count of the number of individuals in each species ID in each year.

surveys %>% 
  group_by(species_id, year) %>% 
  summarize(count = n())

# 3. Use the filter(), group_by(), and summarize() functions to get the mean mass of species DO in each year.
 
 surveys %>%
  filter(species_id == "DO") %>%
  group_by(year) %>%
  summarize(avg_mass = mean(weight, na.rm = TRUE))

```

### 3. Shrub Volume Aggregation (10 pts)


```{r message=FALSE}
shrub_dims <- read_csv('shrub-volume-data.csv')
shrub_dims %>% 
  group_by(experiment) %>% 
  summarize(avg_height = mean(height, na.rm = TRUE),
            max_height = max(height, na.rm = TRUE))
```

### 4. Portal Data Joins (15 pts)

```{r}
# 1.

inner_join(surveys, species, by = "species_id")

# 2.
inner_join(surveys, species, by = "species_id") %>% 
inner_join(., plots, by = "plot_id")

# 3.

surveys %>% 
  inner_join(plots, by = "plot_id") %>% 
  filter(plot_type == "Control")
```

### 5. Portal Data `dplyr` Review (20 pts)

```{r}
surveys %>% 
  inner_join(species, by = "species_id") %>% 
  inner_join(plots, by = "plot_id") %>% 
  filter(plot_type == "Control" | plot_type == "Long-term Krat Exclosure") %>% 
  filter(taxa == "Rodent") %>% 
  select('year', 'genus', 'species', 'weight', 'plot_type') %>% 
  filter(!is.na(weight))
```


### 6. Shrub Volumn Bind (10 pts)


```{r}
new_data <- data.frame(respiratory_rate = c(2.2, 4.0, 6.1, 2.3, 4.1, 6.2, 1.8, 3.5, 5.7, 1.9, 3.5, 5.8, 2.0, 4.7, 6.2),
                       average_temp_C = c(15.1, 20.2, 24.7, 15.2, 22.0, 25.1, 14.2, 19.0, 23.6, 14.9, 20.3, 24.1, 19.2, 22.7, 25.0))

```

```{r}
bind_cols(shrub_dims, new_data)
```

### 7. Shrub Volume Join (10 pts)


```{r message=FALSE}
experiments <- read_csv("https://datacarpentry.org/semester-biology/data/shrub-volume-experiments.csv")
sites <- read_csv("https://datacarpentry.org/semester-biology/data/shrub-volume-sites.csv")
```


```{r}

# 1. Import the experiments data and then use `inner_join` to combine
inner_join(shrub_dims, experiments, by = "experiment")

# 2. Import the sites data and the combine it with both the data on shrub
# dimensions and the data on experiments to produce a single data frame
# that contains all of the data.

shrub_dims_experiments <- inner_join(shrub_dims, experiments, by = "experiment")
shrub_data <- inner_join(shrub_dims_experiments, sites, by = "site")
shrub_data
```

### 8. Extracting vectors from data frames (10 pts)

```{r}
# 1. Use `$` to extract the `weight` column into a vector

shrub_data$latitude

# 2. Use `[]` to extract the `month` column into a vector

shrub_data[["manipulation"]]

#3. Extract the `hindfoot_length` column into a vector and calculate the average value using `mean`. 

mean(shrub_data$width, na.rm = TRUE)
```

### 9. Building data frames from vectors (10 pts)

```{r}
length <- c(2.2, 2.1, 2.7, 3.0, 3.1, 2.5, 1.9, 1.1, 3.5, 2.9)
width <- c(1.3, 2.2, 1.5, 4.5, 3.1, NA, 1.8, 0.5, 2.0, 2.7)
height <- c(9.6, 7.6, 2.2, 1.5, 4.0, 3.0, 4.5, 2.3, 7.5, 3.2)
```

```{r}
data.frame(genus = "Cercidium", species = "microphyllum", length, width, height)
```

